SELECT 
    HISTORY_ID, FLOOR(DAILY_FEE * DURATION * (1 - DISCOUNT_RATE * 0.01)) AS FEE
FROM (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
        COALESCE((
            SELECT DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
            WHERE CAR_TYPE = '트럭' 
              AND DURATION_TYPE =
                CASE 
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
              END
        ), 0) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) R
ORDER BY FEE DESC, HISTORY_ID DESC;