-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ( # 임시 테이블 만듦
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;